
import { Inter } from "next/font/google";
import "./globals.css";
// import Head from "next/head";
import Navbar from "./components/Navbar";
import StoreProvider from "./StoreProvider";
import { Metadata } from "next/dist/lib/metadata/types/metadata-interface";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
        <Navbar/>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
